// Core domain types shared across packages

export type PlanTier = 'free' | 'pro';

export type BookmarkType = 'article' | 'video' | 'image' | 'file' | 'document';

export type CollectionRole = 'owner' | 'editor' | 'viewer';

export type NotificationChannel = 'email' | 'push' | 'in_app';

export interface User {
  id: string;
  email: string;
  name: string;
  plan: PlanTier;
  createdAt: Date;
  updatedAt: Date;
}

export interface Collection {
  id: string;
  ownerId: string;
  title: string;
  icon: string;
  isPublic: boolean;
  shareSlug?: string;
  parentId?: string;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Bookmark {
  id: string;
  ownerId: string;
  collectionId?: string;
  title: string;
  url: string;
  excerpt?: string;
  contentSnapshotPath?: string;
  contentIndexed: boolean;
  type: BookmarkType;
  domain: string;
  coverUrl?: string;
  isDuplicate: boolean;
  isBroken: boolean;
  customOrder?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Tag {
  id: string;
  ownerId: string;
  name: string;
  normalizedName: string;
  color?: string;
  createdAt: Date;
}

export interface Highlight {
  id: string;
  bookmarkId: string;
  ownerId: string;
  textSelected: string;
  color: string;
  annotationMd?: string;
  positionContext: {
    before: string;
    after: string;
    xpath?: string;
  };
  snapshotId?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface File {
  id: string;
  ownerId: string;
  bookmarkId?: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  s3Path: string;
  createdAt: Date;
}

export interface Backup {
  id: string;
  ownerId: string;
  filePath: string;
  sizeBytes: number;
  autoGenerated: boolean;
  createdAt: Date;
}

export interface CollectionPermission {
  id: string;
  collectionId: string;
  userId: string;
  role: CollectionRole;
  createdAt: Date;
}

export interface Reminder {
  id: string;
  bookmarkId: string;
  ownerId: string;
  remindAt: Date;
  notificationChannels: NotificationChannel[];
  completed: boolean;
  createdAt: Date;
}

// ============================================================================
// Request/Response DTOs
// ============================================================================

// Authentication DTOs
export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

// User DTOs
export interface UpdateUserRequest {
  name?: string;
  email?: string;
}

export interface UserStatsResponse {
  totalBookmarks: number;
  totalCollections: number;
  totalTags: number;
  totalHighlights: number;
  storageUsedBytes: number;
}

// Collection DTOs
export interface CreateCollectionRequest {
  title: string;
  icon?: string;
  parentId?: string;
  isPublic?: boolean;
}

export interface UpdateCollectionRequest {
  title?: string;
  icon?: string;
  parentId?: string | null;
  isPublic?: boolean;
  sortOrder?: number;
}

export interface ShareCollectionRequest {
  userId: string;
  role: CollectionRole;
}

// Bookmark DTOs
export interface CreateBookmarkRequest {
  url: string;
  title?: string;
  excerpt?: string;
  collectionId?: string;
  tags?: string[];
  type?: BookmarkType;
  coverUrl?: string;
}

export interface UpdateBookmarkRequest {
  title?: string;
  excerpt?: string;
  collectionId?: string | null;
  tags?: string[];
  coverUrl?: string;
  customOrder?: number;
}

export interface BookmarkWithRelations extends Bookmark {
  tags: Tag[];
  highlights: Highlight[];
}

export interface CreateBookmarkResponse {
  id: string;
  status: 'processing' | 'completed';
  bookmark: BookmarkWithRelations;
}

// Tag DTOs
export interface CreateTagRequest {
  name: string;
  color?: string;
}

export interface UpdateTagRequest {
  name?: string;
  color?: string;
}

export interface MergeTagsRequest {
  sourceTagIds: string[];
  targetTagId: string;
}

// Highlight DTOs
export interface CreateHighlightRequest {
  bookmarkId: string;
  textSelected: string;
  color?: string;
  annotationMd?: string;
  positionContext: {
    before: string;
    after: string;
    xpath?: string;
  };
  snapshotId?: string;
}

export interface UpdateHighlightRequest {
  color?: string;
  annotationMd?: string;
}

// Search DTOs
export interface SearchRequest {
  q?: string;
  tags?: string[];
  type?: BookmarkType[];
  domain?: string[];
  collection?: string;
  dateFrom?: string;
  dateTo?: string;
  fulltext?: boolean;
  page?: number;
  limit?: number;
}

export interface SearchResult {
  id: string;
  title: string;
  url: string;
  excerpt: string;
  highlights: string[];
  score: number;
  bookmark: BookmarkWithRelations;
}

export interface SearchResponse {
  results: SearchResult[];
  total: number;
  page: number;
  limit: number;
  took: number;
}

// File DTOs
export interface UploadFileRequest {
  filename: string;
  mimeType: string;
  bookmarkId?: string;
}

export interface UploadFileResponse {
  id: string;
  uploadUrl: string;
  file: File;
}

// Backup DTOs
export interface GenerateBackupRequest {
  includeSnapshots?: boolean;
}

export interface BackupListResponse {
  backups: Backup[];
  total: number;
}

// Bulk Operations DTOs
export type BulkAction = 'add_tags' | 'remove_tags' | 'move' | 'delete';

export interface BulkActionRequest {
  bookmarkIds: string[];
  action: BulkAction;
  params?: {
    tags?: string[];
    collectionId?: string;
  };
}

export interface BulkActionResponse {
  success: boolean;
  processedCount: number;
  failedCount: number;
  errors?: Array<{
    bookmarkId: string;
    error: string;
  }>;
}

// Import/Export DTOs
export interface ImportHtmlRequest {
  html: string;
}

export interface ImportJsonRequest {
  data: {
    bookmarks: Bookmark[];
    collections: Collection[];
    tags: Tag[];
  };
}

export interface ImportResponse {
  success: boolean;
  importedBookmarks: number;
  importedCollections: number;
  importedTags: number;
  errors?: string[];
}

export type ExportFormat = 'html' | 'csv' | 'txt' | 'json';

export interface ExportRequest {
  collectionId?: string;
  format: ExportFormat;
  includeMetadata?: boolean;
}

// Reminder DTOs
export interface CreateReminderRequest {
  bookmarkId: string;
  remindAt: Date;
  notificationChannels?: NotificationChannel[];
}

export interface UpdateReminderRequest {
  remindAt?: Date;
  notificationChannels?: NotificationChannel[];
  completed?: boolean;
}

// Pagination
export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}
